[font]
size = 12
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "MesloLGS Nerd Font"
style = "normal"

[[font.bold]]
family = "MesloLGS Nerd Font"
style = "Bold"

[[font.italic]]
family = "MesloLGS Nerd Font"
style = "Italic"

[[font.bold_italic]]
family = "MesloLGS Nerd Font"
style = "Bold Italic"
